### ISSUE TITLE
config-server || basic authentication username & password is static in the yaml file

### ISSUE THREAD

**Issue by AbdelrahmanAtia** [AbdelrahmanAtia/instagram-clone#15]
in the application.yml file of config-server we have the following properties:-
```
spring:
  security:
    user:
      name: dev-usr
      password: dev-pwd
```

and as u can see, the basic auth username & password are static..

**TODO**

1- read these senstive values from the .env file
2- update all microservices yaml files that has these info statically to be retrieved from the .env file
